language: node_js

os:
    - osx
    - linux

node_js:
    - 12
    - 14
    - node

services:
    - docker

cache:
    directories:
        - call-router-1.0/node_modules

env:
    global:
        - PORT="3000"
        - HOST="localhost"
        - ACCOUNT_ID="N/A"
        - AUTH_TOKEN="N/A"
        - FC_PHONE_NUMBER="N/A"
    jobs:
        - TEST_DIR=call-router-1.0
        

before_install:
    - npm install -g yarn
    - cd $TEST_DIR

before_script:
    - cd $TEST_DIR

jobs:
    include:
        - stage: lint
          script: yarn lint
        - stage: test
          script:  yarn test:cov

stages:
    - install
    - lint
    - test
