language: node_js

os:
    - osx
    - linux

node_js:
    - 12
    - 14
    - node

services:
    - docker

cache:
    directories:
        - call-router-1.0/node_modules

env:
    global:
        - PORT="3000"
        - HOST="localhost"
        - ACCOUNT_ID="N/A"
        - AUTH_TOKEN="N/A"
        - FC_PHONE_NUMBER="N/A"
    jobs:
        - TEST_DIR=call-router-1.0

jobs:
    include:
        - stage: install
          script: cd $TEST_DIR && yarn install
        - stage: lint
          script: cd $TEST_DIR && yarn lint
        - stage: test
          script: cd $TEST_DIR && yarn test:cov

stages:
    - install
    - lint
    - test
