name: Call Router 1.0 CI
on: [push]

defaults:
  run:
    working-directory: call-router-1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Static Code Analysis
        run: yarn lint
      - name: Test
        run: yarn test:cov
        env:
          AUTH_TOKEN: "N/A"
          ACCOUNT_ID: "N/A"
          APPLICATION_ID: "N/A"
          FC_NUMBER: "N/A"
          PORT: "3000"
          HOST: "N/A"

      
