name: Call Router Sample Apps CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        working-directory: call-router-1.0
        run: yarn install --frozen-lockfile
      - name: Static Code Analysis
        working-directory: call-router-1.0
        run: yarn lint
      - name: Test
        working-directory: call-router-1.0
        run: yarn test:cov

      
